version: '3'
services:
  app:
    image: fthkhouloud/springbootapp
    container_name: springbootapp
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/ProjetKhouloud
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ProjetKhouloud
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes